### ISSUE TITLE
README.md link errors

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS/deep-archive#131]
Several of the links in the [README.md](https://github.com/NASA-PDS/deep-archive#readme) do not work because they are missing the "index.html" part of the link.  When you click on them you get a 404 error, and a reminder to add index.html to your address line.  Either a server setting needs to be reset or the links need to be more explicit.  Examples include the [Installation](https://nasa-pds.github.io/pds-deep-archive/installation/) and [Development Guide](https://nasa-pds.github.io/pds-deep-archive/development/).  Note that these are exact cut and paste from the README.md file.

**Comment by jordanpadams** [comment]
@tbarnes4 one more shot at fix. referenced the wrong ticket in the commit message, but here is the fix: https://github.com/NASA-PDS/deep-archive/commit/16f40a3825c9ca154562daa7358d6a2560b34fc0

**Comment by jordanpadams** [comment]
👍
