### ISSUE TITLE
integrate deep archive to staging tests

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/deep-archive#138]
## 💡 Description

See ticket https://github.com/NASA-PDS/pds-api/issues/240

The deployment and execution of deep-archive should be triggered by jenkins on the platform already intiated for registry-api and doi-service.

**Comment by jimmie** [comment]
work continues as time permits

**Comment by tloubrieu-jpl** [comment]
work continues as time permits

**Comment by nutjob4life** [comment]
There are two pull-requests awaiting review for this issue:

- [from registry](https://github.com/NASA-PDS/registry/pull/163)
- [from deep-archive](https://github.com/NASA-PDS/deep-archive/pull/142)
