### ISSUE TITLE
Canonical path is not processed correctly ('/../ in path)

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/deep-archive#145]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I ran Validate on the 2 submitted packages from https://github.com/NASA-PDS/operations/issues/373, it failed. Using the `vo mawd` package as an example, here is the error:

> ERROR  [error.table.field_value_data_type_mismatch]   data object 1, record 11, field 2: Value does not match its data type 'ASCII_File_Specification_Name': The directory spec '/document/../catalog/' does not match the pattern '/?([A-Za-z0-9][A-Za-z0-9_-]*[A-Za-z0-9]/?|[A-Za-z0-9][^-_]/?)*'

Looking at the offending [transfer manifest tab](https://github.com/NASA-PDS/deep-archive/files/11116407/vo_mawd_v1.0_20230313_transfer_manifest_v1.0.tab.txt) file, there are paths such as `/document/../catalog/dataset.cat`. 

Looking at the [sip tab](https://github.com/NASA-PDS/deep-archive/files/11116433/vo_mawd_v1.0_20230313_sip_v1.0.tab.txt) file, this corresponds to `https://pds-atmospheres.nmsu.edu/PDS/data/vo_3001/document/../catalog/dataset.cat`.

### 🕵️ Expected behavior

I expected Deep Archive to massage these URLs into a format acceptable by PDS.

### 📜 To Reproduce

1. Run Validate v3.3.1 on the NSSDCA Delivery Package from https://github.com/NASA-PDS/operations/issues/373
2. Read the Validate report

### 🖥 Environment Info

?

### 📚 Version of Software Used

?

### 🩺 Test Data / Additional context

**NSSDCA delivery package:** https://github.com/NASA-PDS/operations/files/10960033/pdsatm_pack9_20230313.tar.gz

**Validate reports:**
- [vo_irtm_v1.0_20230313-validate.txt](https://github.com/NASA-PDS/deep-archive/files/11116498/vo_irtm_v1.0_20230313-validate.txt)
- [vo_mawd_v1.0_20230313-validate.txt](https://github.com/NASA-PDS/deep-archive/files/11116499/vo_mawd_v1.0_20230313-validate.txt)

**Comment by nutjob4life** [comment]
@c-suh @jordanpadams is it possible to get the original files from the Atmosphere node (as well as the command they ran) that produced the incorrect SIP? I'd like to first make sure I can reproduce this by running `pds-deep-archive` against those files and making sure I see `/../` in the output.

**Comment by nutjob4life** [comment]
Thanks @jordanpadams.

FYI for my own reference, here's a command I came up with to mirror an HTTPD index listing and all its file:
```
wget \
    --cut-dirs=2 \
    --execute robots=off \
    --mirror \
    --no-check-certificate \
    --no-host-directories \
    --no-parent \
    --quiet \
    --recursive \
    --reject='index.html*' \
    --relative \
    --timestamping \
    https://pds-atmospheres.nmsu.edu/PDS/data/vo_3002/
```

**Comment by nutjob4life** [comment]
@c-suh @jordanpadams okay so in the source data as provided by the Atmospheres node in `data/vo_3002/document/dataset.xml`, there's this:
```xml
        <Document_Edition>
            <edition_name>ASCII Text</edition_name>
            <language>English</language>
            <files>1</files>
            <Document_File>
                <file_name>../catalog/dataset.cat</file_name> <!--  👈notice -->
                <local_identifier>vo_irtm_dataset_cat</local_identifier>
                <document_standard_id>7-Bit ASCII Text</document_standard_id>
            </Document_File>
        </Document_Edition>
```
Before I fix this, my first question is: is this legal in a PDS label?

**Comment by tloubrieu-jpl** [comment]
@nutjob4life ☝️

**Comment by nutjob4life** [comment]
@tloubrieu-jpl @c-suh https://jpl.slack.com/archives/GCGR1R3A4/p1680820436039979

**Comment by c-suh** [comment]
@tloubrieu-jpl there's a link in the description under "Test Data/Additional Context" to the package which showed this error. However, just in case they've replaced it, here is the one I had saved locally: [pdsatm_pack9_20230313.tar.gz](https://github.com/NASA-PDS/deep-archive/files/11388605/pdsatm_pack9_20230313.tar.gz).
