### ISSUE TITLE
Upgrade deep-archive to comply with latest search API changes (API v1.4.0 / pds-api-client v1.5.0)

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/deep-archive#159]
### 💡 Description

The code of deep archive need to be updated to comply with the new pagination parameters in the PDS API. The manual on how this has been updated is available in the PR https://github.com/NASA-PDS/pds-api/pull/279 (not published yet).

In a few words, `start` parameter becomes `search-after`. `search-after` needs to be used with parameter `sort`, it is advised to use it with parameter, `sort=ops:Harvest_Info.ops:harvest_date_time`. And, for each new page, `search-after` is set to the latest of the harvest date time found in the previous result. 

The code to query the API as needed by deep-archive as been updated in the pds.api_client tests, there: https://github.com/NASA-PDS/pds-api-client/pull/33/files#r1488651568

The pre-release of the version 1.5.0 of the `pds.api_client` is available on test pypi, see https://test.pypi.org/project/pds.api-client/1.5.0/

The version 1.4.0 of the API is deployed on gamma https://pds.nasa.gov/api/search-en-gamma/1/

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life, is the ticket https://github.com/NASA-PDS/pds-api-client/issues/34 still blocking this ticket ?

**Comment by nutjob4life** [comment]
@tloubrieu-jpl no, it is no longer blocking. Thanks for asking.

**Comment by tloubrieu-jpl** [comment]
Great thanks.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life, I was asking to see if we should plan to deploy the new version of the API and stable release of deep-archive tomorrow but since it is before the week-end, I might as well wait for this Monday.
